<a href="https://colab.research.google.com/github/gokul2557/ML/blob/main/EX1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving students.csv to students.csv

In [ ]:
import pandas as pd
df =pd.read_csv("students.csv")

In [ ]:
df.head()

   Weight  Height  Age Gender
0      79    1.80   35   Male
1      69    1.68   39   Male
2      73    1.82   25   Male
3      95    1.70   60   Male
4      82    1.87   27   Male

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Weight  10 non-null     int64
 1   Height  10 non-null     float64
 2   Age     10 non-null     int64
 3   Gender  10 non-null     object
dtypes: float64(1), int64(2), object(1)
memory usage: 452.0+ bytes

In [ ]:
df.describe()

          Weight     Height        Age
count  10.000000  10.000000  10.000000
mean   72.600000   1.701000  40.300000
std    10.834103   0.118832  22.181323
min    55.000000   1.500000  16.000000
25%    69.000000   1.647500  25.500000
50%    70.000000   1.690000  37.000000
75%    77.500000   1.795000  49.500000
max    95.000000   1.870000  89.000000

In [ ]:
df["Gender"] = df["Gender"].map({"Male": 1, "Female": 0})

df

   Weight  Height  Age  Gender
0      79    1.80   35       1
1      69    1.68   39       1
2      73    1.82   25       1
3      95    1.70   60       1
4      82    1.87   27       1
5      55    1.55   18       0
6      69    1.50   89       0
7      71    1.78   42       0
8      64    1.67   16       0
9      69    1.64   52       0

In [ ]:
X=df[["Height","Age","Gender"]]
y=df["Weight"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train ,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)

print("Predicted Weights:")
print(y_pred)

Predicted Weights:
[56.85651025 79.10576115]

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

Mean Squared Error: 76.57792714844265
R2 Score: -11.252468343750825

In [ ]:
print("Intercept:", model.intercept_)

print("Height Coefficient:", model.coef_[0])
print("Age Coefficient:", model.coef_[1])
print("Gender Coefficient:", model.coef_[2])

Intercept: -3.0552172392595196
Height Coefficient: 32.83533630032696
Age Coefficient: 0.3172947417608091
Gender Coefficient: 14.623118479712073

In [ ]:
new_person = pd.DataFrame({
    "Height": [1.75],
    "Age": [24],
    "Gender": [1]   # Male = 1, Female = 0
})

predicted_weight = model.predict(new_person)

print("Predicted Weight:", predicted_weight[0], "kg")

Predicted Weight: 76.64481356828415 kg

In [ ]:
new_person = pd.DataFrame({
    "Height": [1.8],
    "Age": [35],
    "Gender": [1]   # Male = 1, Female = 0
})

predicted_weight = model.predict(new_person)

print("Predicted Weight:", predicted_weight[0], "kg")

Predicted Weight: 81.7768225426694 kg